repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 9b1e9a33f1b33f6ecc2fdbb8d7cc894e951106e4  # frozen: v0.14.13
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: bb4666ad77b539a6b4ce4eda7ebb6de553704021  # frozen: v1.42.0
    hooks:
      - id: typos
