name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'meta:skip-test'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      - run: uv run --python=3.12 --dev pytest --cov --cov-report html --cov-report term-missing -svv --durations=40 -ra
        env:
          COVERAGE_CORE: sysmon
